image: blang/latex
build:
  script:
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"

build:
  script:
    - latexmk -pdf -cd dissertation/dissertation.tex
  artifacts:
    paths:
      - "*.pdf"
