# Generated by Django 2.1.5 on 2019-01-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptSpeare', '0003_auto_20190122_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
