# Generated by Django 2.1.5 on 2019-01-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptSpeare', '0004_play_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
