# Generated by Django 2.1.5 on 2019-01-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptSpeare', '0005_interpretation_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
