# Generated by Django 2.1.5 on 2019-02-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptSpeare', '0006_auto_20190128_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpretation',
            name='lead',
        ),
        migrations.AddField(
            model_name='interpretation',
            name='accent',
            field=models.CharField(choices=[('UK', 'UK'), ('US', 'US')], default='UK', max_length=2),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='female_lead_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interpretation',
            name='male_lead_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interpretation',
            name='type',
            field=models.CharField(choices=[('Film', 'Film'), ('Stage', 'Stage'), ('Audio', 'Audio')], default='Film', max_length=10),
        ),
        migrations.AddField(
            model_name='play',
            name='abbreviation',
            field=models.CharField(default=3, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
