# Generated by Django 2.1.5 on 2019-02-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptSpeare', '0007_auto_20190206_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interpretation',
            name='female_lead_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='year',
            field=models.CharField(default=1900, max_length=4),
        ),
    ]
